services:
  postgres:
    container_name: postgres_container
    image: postgres:16
    environment:
      POSTGRES_DB: "socialNetworkV01"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "HKNpYyXCm2"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - DBdata-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres

volumes:
  DBdata-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge